# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _canarin_loramsg
else:
    import _canarin_loramsg

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)



def cdata(ptr, nelements=1):
    return _canarin_loramsg.cdata(ptr, nelements)

def memmove(data, indata):
    return _canarin_loramsg.memmove(data, indata)

def ntoh_s_packet(BOTH, len):
    return _canarin_loramsg.ntoh_s_packet(BOTH, len)

def hton_s_packet(BOTH):
    return _canarin_loramsg.hton_s_packet(BOTH)

def ntoh_s_packet_ack(BOTH, len):
    return _canarin_loramsg.ntoh_s_packet_ack(BOTH, len)

def hton_s_packet_ack(BOTH):
    return _canarin_loramsg.hton_s_packet_ack(BOTH)
class intArray(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, nelements):
        _canarin_loramsg.intArray_swiginit(self, _canarin_loramsg.new_intArray(nelements))
    __swig_destroy__ = _canarin_loramsg.delete_intArray

    def __getitem__(self, index):
        return _canarin_loramsg.intArray___getitem__(self, index)

    def __setitem__(self, index, value):
        return _canarin_loramsg.intArray___setitem__(self, index, value)

    def cast(self):
        return _canarin_loramsg.intArray_cast(self)

    @staticmethod
    def frompointer(t):
        return _canarin_loramsg.intArray_frompointer(t)

# Register intArray in _canarin_loramsg:
_canarin_loramsg.intArray_swigregister(intArray)

def intArray_frompointer(t):
    return _canarin_loramsg.intArray_frompointer(t)

AGGREGRATE_TOGETHER_MAX = _canarin_loramsg.AGGREGRATE_TOGETHER_MAX
BASE_TIMESTAMP = _canarin_loramsg.BASE_TIMESTAMP
ST_NR_ERROR = _canarin_loramsg.ST_NR_ERROR
ST_NR_INTERVAL = _canarin_loramsg.ST_NR_INTERVAL
ST_GLAT = _canarin_loramsg.ST_GLAT
ST_GLNG = _canarin_loramsg.ST_GLNG
ST_GALT = _canarin_loramsg.ST_GALT
ST_TEMP = _canarin_loramsg.ST_TEMP
ST_HUMI = _canarin_loramsg.ST_HUMI
ST_PRES = _canarin_loramsg.ST_PRES
ST_PM2_5 = _canarin_loramsg.ST_PM2_5
ST_PM10 = _canarin_loramsg.ST_PM10
ST_PM1 = _canarin_loramsg.ST_PM1
ST_VOLT = _canarin_loramsg.ST_VOLT
ST_FORM = _canarin_loramsg.ST_FORM
ST_STATUS = _canarin_loramsg.ST_STATUS
ST_MQ7CO = _canarin_loramsg.ST_MQ7CO
ST_WZSHCHO = _canarin_loramsg.ST_WZSHCHO
ST_MHZ16CO2 = _canarin_loramsg.ST_MHZ16CO2
ST_INIT_PKT = _canarin_loramsg.ST_INIT_PKT
ST_GLAT_INT = _canarin_loramsg.ST_GLAT_INT
ST_GLAT_FRAC = _canarin_loramsg.ST_GLAT_FRAC
ST_GLNG_INT = _canarin_loramsg.ST_GLNG_INT
ST_GLNG_FRAC = _canarin_loramsg.ST_GLNG_FRAC
ST_GALT_INT = _canarin_loramsg.ST_GALT_INT
ST_ACK = _canarin_loramsg.ST_ACK
ST_MAX = _canarin_loramsg.ST_MAX
class s_data(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    seq = property(_canarin_loramsg.s_data_seq_get, _canarin_loramsg.s_data_seq_set)
    is_negative = property(_canarin_loramsg.s_data_is_negative_get, _canarin_loramsg.s_data_is_negative_set)
    num_bytes = property(_canarin_loramsg.s_data_num_bytes_get, _canarin_loramsg.s_data_num_bytes_set)
    sensor_type = property(_canarin_loramsg.s_data_sensor_type_get, _canarin_loramsg.s_data_sensor_type_set)
    data = property(_canarin_loramsg.s_data_data_get)

    def __init__(self):
        _canarin_loramsg.s_data_swiginit(self, _canarin_loramsg.new_s_data())
    __swig_destroy__ = _canarin_loramsg.delete_s_data

# Register s_data in _canarin_loramsg:
_canarin_loramsg.s_data_swigregister(s_data)
cvar = _canarin_loramsg.cvar

class s_single_packet(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    is_single = property(_canarin_loramsg.s_single_packet_is_single_get, _canarin_loramsg.s_single_packet_is_single_set)
    timestamp = property(_canarin_loramsg.s_single_packet_timestamp_get, _canarin_loramsg.s_single_packet_timestamp_set)
    header = property(_canarin_loramsg.s_single_packet_header_get, _canarin_loramsg.s_single_packet_header_set)
    data = property(_canarin_loramsg.s_single_packet_data_get)

    def __init__(self):
        _canarin_loramsg.s_single_packet_swiginit(self, _canarin_loramsg.new_s_single_packet())
    __swig_destroy__ = _canarin_loramsg.delete_s_single_packet

# Register s_single_packet in _canarin_loramsg:
_canarin_loramsg.s_single_packet_swigregister(s_single_packet)

class s_multi_packet(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    is_single = property(_canarin_loramsg.s_multi_packet_is_single_get, _canarin_loramsg.s_multi_packet_is_single_set)
    timestamp = property(_canarin_loramsg.s_multi_packet_timestamp_get, _canarin_loramsg.s_multi_packet_timestamp_set)
    header = property(_canarin_loramsg.s_multi_packet_header_get, _canarin_loramsg.s_multi_packet_header_set)
    n_data = property(_canarin_loramsg.s_multi_packet_n_data_get, _canarin_loramsg.s_multi_packet_n_data_set)
    data = property(_canarin_loramsg.s_multi_packet_data_get)

    def __init__(self):
        _canarin_loramsg.s_multi_packet_swiginit(self, _canarin_loramsg.new_s_multi_packet())
    __swig_destroy__ = _canarin_loramsg.delete_s_multi_packet

# Register s_multi_packet in _canarin_loramsg:
_canarin_loramsg.s_multi_packet_swigregister(s_multi_packet)

class s_ack(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    nmembers = property(_canarin_loramsg.s_ack_nmembers_get, _canarin_loramsg.s_ack_nmembers_set)
    ids = property(_canarin_loramsg.s_ack_ids_get)

    def __init__(self):
        _canarin_loramsg.s_ack_swiginit(self, _canarin_loramsg.new_s_ack())
    __swig_destroy__ = _canarin_loramsg.delete_s_ack

# Register s_ack in _canarin_loramsg:
_canarin_loramsg.s_ack_swigregister(s_ack)

class s_packet(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    single = property(_canarin_loramsg.s_packet_single_get, _canarin_loramsg.s_packet_single_set)
    multi = property(_canarin_loramsg.s_packet_multi_get, _canarin_loramsg.s_packet_multi_set)
    ack = property(_canarin_loramsg.s_packet_ack_get, _canarin_loramsg.s_packet_ack_set)

    def __init__(self):
        _canarin_loramsg.s_packet_swiginit(self, _canarin_loramsg.new_s_packet())
    __swig_destroy__ = _canarin_loramsg.delete_s_packet

# Register s_packet in _canarin_loramsg:
_canarin_loramsg.s_packet_swigregister(s_packet)

SD_INT = _canarin_loramsg.SD_INT
SD_FLOAT = _canarin_loramsg.SD_FLOAT
SD_STR = _canarin_loramsg.SD_STR
SD_MAX = _canarin_loramsg.SD_MAX

def get_sensor_type(ext):
    return _canarin_loramsg.get_sensor_type(ext)

def get_s_data_size(sd):
    return _canarin_loramsg.get_s_data_size(sd)

def make_sensor_data_int(sensor_type, seq, data):
    return _canarin_loramsg.make_sensor_data_int(sensor_type, seq, data)

def make_sensor_data_float(sensor_type, seq, data):
    return _canarin_loramsg.make_sensor_data_float(sensor_type, seq, data)

def make_sensor_data_string(sensor_type, seq, data, data_len):
    return _canarin_loramsg.make_sensor_data_string(sensor_type, seq, data, data_len)

def free_sensor_data(sd):
    return _canarin_loramsg.free_sensor_data(sd)

def parse_sensor_data_int(sd):
    return _canarin_loramsg.parse_sensor_data_int(sd)

def parse_sensor_data_float(sd):
    return _canarin_loramsg.parse_sensor_data_float(sd)

def parse_sensor_string(sd):
    return _canarin_loramsg.parse_sensor_string(sd)

def make_packet(timestamp, sds, num_data, out_len):
    return _canarin_loramsg.make_packet(timestamp, sds, num_data, out_len)

def make_ack_packet(nmembers, ids):
    return _canarin_loramsg.make_ack_packet(nmembers, ids)

def free_packet(packet):
    return _canarin_loramsg.free_packet(packet)

def bin_to_s_packet(data):
    return _canarin_loramsg.bin_to_s_packet(data)

def is_single_packet(packet):
    return _canarin_loramsg.is_single_packet(packet)

def get_packet_n_data(packet):
    return _canarin_loramsg.get_packet_n_data(packet)

def get_packet_timestamp(packet):
    return _canarin_loramsg.get_packet_timestamp(packet)

def get_packet_ack_length(packet):
    return _canarin_loramsg.get_packet_ack_length(packet)

def parse_packet(packet, index):
    return _canarin_loramsg.parse_packet(packet, index)


