/*
 * Auto generated by scripts/generate/generate_hazemon_types.py
 */

#include <string.h>
#include "can5_hazemon_types.h"
#include "can5_utils.h"


static const hazemon_type_token_t hazemon_type_tokens[] = {
$hazemon_type_tokens
};


const hazemon_type_token_t *can5_hazemon_get_type(const hazemon_type_t type)
{
    for(size_t i = 0; i < sizeof(hazemon_type_tokens)/sizeof(hazemon_type_tokens[0]); i ++) {
        if (hazemon_type_tokens[i].type == type) {
            return &hazemon_type_tokens[i];
        }
    }
    return NULL;
}


const hazemon_type_token_t *can5_hazemon_get_token(const char *token)
{
    for(size_t i = 0; i < sizeof(hazemon_type_tokens)/sizeof(hazemon_type_tokens[0]); i ++) {
        if (strcmp(hazemon_type_tokens[i].token, token) == 0) {
            return &hazemon_type_tokens[i];
        }
    }
    return NULL;
}


static const can5_tag_tab_t __hazemon_type_tags = {
$tag_tab
};


const char *hazemon_type_str(const hazemon_type_t type)
{
    return TAG_LOOKUP(type, __hazemon_type_tags);
}

