/*
 * Auto generated by scripts/generate/generate_hazemon_types.py
 */

#ifndef __CAN5_HAZEMON_TYPES_H__
#define __CAN5_HAZEMON_TYPES_H__

typedef enum hazemon_type_e {
$hazemon_type_enum
    HAZEMON_TYPE_LAST,
} hazemon_type_t;

typedef struct hazemon_type_token_s {
   const char       *token;
   hazemon_type_t   type;
   const char       *datatype;
   float            multiplier;
} hazemon_type_token_t;


const hazemon_type_token_t *can5_get_hazemon_t_type(const hazemon_type_t type);
const hazemon_type_token_t *can5_get_hazemon_t_token(const char *token);
const char *hazemon_type_str(const hazemon_type_t type);

#endif /* __CAN5_HAZEMON_TYPES_H__ */