# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _can5_loramsg
else:
    import _can5_loramsg

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)



def cdata(ptr, nelements=1):
    return _can5_loramsg.cdata(ptr, nelements)

def memmove(data, indata):
    return _can5_loramsg.memmove(data, indata)

def can5_lmsg_ntoh_packet(packet, len):
    return _can5_loramsg.can5_lmsg_ntoh_packet(packet, len)

def can5_lmsg_hton_packet(packet):
    return _can5_loramsg.can5_lmsg_hton_packet(packet)

def can5_lmsg_ntoh_packet_ack(packet, len):
    return _can5_loramsg.can5_lmsg_ntoh_packet_ack(packet, len)

def can5_lmsg_hton_packet_ack(packet):
    return _can5_loramsg.can5_lmsg_hton_packet_ack(packet)
class intArray(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, nelements):
        _can5_loramsg.intArray_swiginit(self, _can5_loramsg.new_intArray(nelements))
    __swig_destroy__ = _can5_loramsg.delete_intArray

    def __getitem__(self, index):
        return _can5_loramsg.intArray___getitem__(self, index)

    def __setitem__(self, index, value):
        return _can5_loramsg.intArray___setitem__(self, index, value)

    def cast(self):
        return _can5_loramsg.intArray_cast(self)

    @staticmethod
    def frompointer(t):
        return _can5_loramsg.intArray_frompointer(t)

# Register intArray in _can5_loramsg:
_can5_loramsg.intArray_swigregister(intArray)

def intArray_frompointer(t):
    return _can5_loramsg.intArray_frompointer(t)

AGGREGRATE_TOGETHER_MAX = _can5_loramsg.AGGREGRATE_TOGETHER_MAX
BASE_TIMESTAMP = _can5_loramsg.BASE_TIMESTAMP
LMSG_GLAT = _can5_loramsg.LMSG_GLAT
LMSG_GLNG = _can5_loramsg.LMSG_GLNG
LMSG_GALT = _can5_loramsg.LMSG_GALT
LMSG_TEMP = _can5_loramsg.LMSG_TEMP
LMSG_HUMI = _can5_loramsg.LMSG_HUMI
LMSG_PRES = _can5_loramsg.LMSG_PRES
LMSG_PM2_5 = _can5_loramsg.LMSG_PM2_5
LMSG_PM10 = _can5_loramsg.LMSG_PM10
LMSG_PM1 = _can5_loramsg.LMSG_PM1
LMSG_CO = _can5_loramsg.LMSG_CO
LMSG_MQ7CO = _can5_loramsg.LMSG_MQ7CO
LMSG_MHZ16CO2 = _can5_loramsg.LMSG_MHZ16CO2
LMSG_NO2 = _can5_loramsg.LMSG_NO2
LMSG_VOLT = _can5_loramsg.LMSG_VOLT
LMSG_WZSHCHO = _can5_loramsg.LMSG_WZSHCHO
LMSG_RAIN = _can5_loramsg.LMSG_RAIN
LMSG_WIND_SPD = _can5_loramsg.LMSG_WIND_SPD
LMSG_WIND_DIR = _can5_loramsg.LMSG_WIND_DIR
LMSG_FORM = _can5_loramsg.LMSG_FORM
LMSG_STATUS = _can5_loramsg.LMSG_STATUS
LMSG_ACK = _can5_loramsg.LMSG_ACK
LMSG_NR_ERROR = _can5_loramsg.LMSG_NR_ERROR
LMSG_NR_INTERVAL = _can5_loramsg.LMSG_NR_INTERVAL
LMSG_MAX = _can5_loramsg.LMSG_MAX
class can5_lmsg_data(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    seq = property(_can5_loramsg.can5_lmsg_data_seq_get, _can5_loramsg.can5_lmsg_data_seq_set)
    cycle_id = property(_can5_loramsg.can5_lmsg_data_cycle_id_get, _can5_loramsg.can5_lmsg_data_cycle_id_set)
    is_negative = property(_can5_loramsg.can5_lmsg_data_is_negative_get, _can5_loramsg.can5_lmsg_data_is_negative_set)
    num_bytes = property(_can5_loramsg.can5_lmsg_data_num_bytes_get, _can5_loramsg.can5_lmsg_data_num_bytes_set)
    sensor_type = property(_can5_loramsg.can5_lmsg_data_sensor_type_get, _can5_loramsg.can5_lmsg_data_sensor_type_set)
    data = property(_can5_loramsg.can5_lmsg_data_data_get)

    def __init__(self):
        _can5_loramsg.can5_lmsg_data_swiginit(self, _can5_loramsg.new_can5_lmsg_data())
    __swig_destroy__ = _can5_loramsg.delete_can5_lmsg_data

# Register can5_lmsg_data in _can5_loramsg:
_can5_loramsg.can5_lmsg_data_swigregister(can5_lmsg_data)

class can5_lmsg_single_packet(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    is_single = property(_can5_loramsg.can5_lmsg_single_packet_is_single_get, _can5_loramsg.can5_lmsg_single_packet_is_single_set)
    timestamp = property(_can5_loramsg.can5_lmsg_single_packet_timestamp_get, _can5_loramsg.can5_lmsg_single_packet_timestamp_set)
    header = property(_can5_loramsg.can5_lmsg_single_packet_header_get, _can5_loramsg.can5_lmsg_single_packet_header_set)
    data = property(_can5_loramsg.can5_lmsg_single_packet_data_get)

    def __init__(self):
        _can5_loramsg.can5_lmsg_single_packet_swiginit(self, _can5_loramsg.new_can5_lmsg_single_packet())
    __swig_destroy__ = _can5_loramsg.delete_can5_lmsg_single_packet

# Register can5_lmsg_single_packet in _can5_loramsg:
_can5_loramsg.can5_lmsg_single_packet_swigregister(can5_lmsg_single_packet)

class can5_lmsg_multi_packet(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    is_single = property(_can5_loramsg.can5_lmsg_multi_packet_is_single_get, _can5_loramsg.can5_lmsg_multi_packet_is_single_set)
    timestamp = property(_can5_loramsg.can5_lmsg_multi_packet_timestamp_get, _can5_loramsg.can5_lmsg_multi_packet_timestamp_set)
    header = property(_can5_loramsg.can5_lmsg_multi_packet_header_get, _can5_loramsg.can5_lmsg_multi_packet_header_set)
    n_data = property(_can5_loramsg.can5_lmsg_multi_packet_n_data_get, _can5_loramsg.can5_lmsg_multi_packet_n_data_set)
    data = property(_can5_loramsg.can5_lmsg_multi_packet_data_get)

    def __init__(self):
        _can5_loramsg.can5_lmsg_multi_packet_swiginit(self, _can5_loramsg.new_can5_lmsg_multi_packet())
    __swig_destroy__ = _can5_loramsg.delete_can5_lmsg_multi_packet

# Register can5_lmsg_multi_packet in _can5_loramsg:
_can5_loramsg.can5_lmsg_multi_packet_swigregister(can5_lmsg_multi_packet)

LMSG_ACK_TYPE_DATA = _can5_loramsg.LMSG_ACK_TYPE_DATA
LMSG_ACK_TYPE_RESTART = _can5_loramsg.LMSG_ACK_TYPE_RESTART
LMSG_ACK_TYPE_INTERVAL = _can5_loramsg.LMSG_ACK_TYPE_INTERVAL
LMSG_ACK_TYPE_RESET_FRAME_COUNTER = _can5_loramsg.LMSG_ACK_TYPE_RESET_FRAME_COUNTER
LMSG_ACK_TYPE_REJOIN = _can5_loramsg.LMSG_ACK_TYPE_REJOIN
class can5_lmsg_ack(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    cycle_id = property(_can5_loramsg.can5_lmsg_ack_cycle_id_get, _can5_loramsg.can5_lmsg_ack_cycle_id_set)
    type = property(_can5_loramsg.can5_lmsg_ack_type_get, _can5_loramsg.can5_lmsg_ack_type_set)
    data = property(_can5_loramsg.can5_lmsg_ack_data_get, _can5_loramsg.can5_lmsg_ack_data_set)

    def __init__(self):
        _can5_loramsg.can5_lmsg_ack_swiginit(self, _can5_loramsg.new_can5_lmsg_ack())
    __swig_destroy__ = _can5_loramsg.delete_can5_lmsg_ack

# Register can5_lmsg_ack in _can5_loramsg:
_can5_loramsg.can5_lmsg_ack_swigregister(can5_lmsg_ack)

class can5_lmsg_packet(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    single = property(_can5_loramsg.can5_lmsg_packet_single_get, _can5_loramsg.can5_lmsg_packet_single_set)
    multi = property(_can5_loramsg.can5_lmsg_packet_multi_get, _can5_loramsg.can5_lmsg_packet_multi_set)
    ack = property(_can5_loramsg.can5_lmsg_packet_ack_get, _can5_loramsg.can5_lmsg_packet_ack_set)

    def __init__(self):
        _can5_loramsg.can5_lmsg_packet_swiginit(self, _can5_loramsg.new_can5_lmsg_packet())
    __swig_destroy__ = _can5_loramsg.delete_can5_lmsg_packet

# Register can5_lmsg_packet in _can5_loramsg:
_can5_loramsg.can5_lmsg_packet_swigregister(can5_lmsg_packet)

LMSG_DT_INT = _can5_loramsg.LMSG_DT_INT
LMSG_DT_FLOAT = _can5_loramsg.LMSG_DT_FLOAT
LMSG_DT_STR = _can5_loramsg.LMSG_DT_STR
LMSG_DT_INVALID = _can5_loramsg.LMSG_DT_INVALID
LMSG_DT_MAX = _can5_loramsg.LMSG_DT_MAX

def can5_lmsg_get_data_size(sd):
    return _can5_loramsg.can5_lmsg_get_data_size(sd)

def can5_lmsg_get_datatype(sensor_type):
    return _can5_loramsg.can5_lmsg_get_datatype(sensor_type)

def can5_lmsg_get_precision(sensor_type):
    return _can5_loramsg.can5_lmsg_get_precision(sensor_type)

def can5_lmsg_make_sensor_data(sensor_type, cycle_id, seq, data):
    return _can5_loramsg.can5_lmsg_make_sensor_data(sensor_type, cycle_id, seq, data)

def can5_lmsg_make_sensor_data_string(sensor_type, cycle_id, seq, data, data_len):
    return _can5_loramsg.can5_lmsg_make_sensor_data_string(sensor_type, cycle_id, seq, data, data_len)

def can5_lmsg_free_sensor_data(sd):
    return _can5_loramsg.can5_lmsg_free_sensor_data(sd)

def can5_lmsg_parse_sensor_data(sd):
    return _can5_loramsg.can5_lmsg_parse_sensor_data(sd)

def can5_lmsg_parse_sensor_string(sd):
    return _can5_loramsg.can5_lmsg_parse_sensor_string(sd)

def can5_lmsg_make_packet(timestamp, sds, num_data, out_len):
    return _can5_loramsg.can5_lmsg_make_packet(timestamp, sds, num_data, out_len)

def can5_lmsg_make_ack_packet(type, val, nmembers, id, seqs):
    return _can5_loramsg.can5_lmsg_make_ack_packet(type, val, nmembers, id, seqs)

def can5_lmsg_free_packet(packet):
    return _can5_loramsg.can5_lmsg_free_packet(packet)

def can5_lmsg_bin_to_packet(data):
    return _can5_loramsg.can5_lmsg_bin_to_packet(data)

def can5_lmsg_is_single_packet(packet):
    return _can5_loramsg.can5_lmsg_is_single_packet(packet)

def can5_lmsg_get_packet_n_data(packet):
    return _can5_loramsg.can5_lmsg_get_packet_n_data(packet)

def can5_lmsg_get_packet_timestamp(packet):
    return _can5_loramsg.can5_lmsg_get_packet_timestamp(packet)

def can5_lmsg_get_packet_ack_length(packet):
    return _can5_loramsg.can5_lmsg_get_packet_ack_length(packet)

def can5_lmsg_parse_packet(packet, index):
    return _can5_loramsg.can5_lmsg_parse_packet(packet, index)


