/*
 * Auto generated by scripts/generate/generate_hazemon_types.py
 */

#ifndef __CAN5_HAZEMON_TYPES_H__
#define __CAN5_HAZEMON_TYPES_H__

#include <sys/queue.h>

typedef enum hazemon_type_e {
    HAZEMON_INTERVAL         = 0 ,
    HAZEMON_GPS_LAT          = 1 ,
    HAZEMON_GPS_LNG          = 2 ,
    HAZEMON_GPS_ALT          = 3 ,
    HAZEMON_TEMPERATURE      = 4 ,
    HAZEMON_HUMIDITY         = 5 ,
    HAZEMON_PRESSURE         = 6 ,
    HAZEMON_PM2_5            = 7 ,
    HAZEMON_PM10             = 8 ,
    HAZEMON_PM1_0            = 9 ,
    HAZEMON_BATT_V           = 10,
    HAZEMON_FORMALDEHYDE     = 11,
    HAZEMON_STATUS           = 12,
    HAZEMON_NH3              = 13,
    HAZEMON_CO               = 14,
    HAZEMON_NO2              = 15,
    HAZEMON_C3H8             = 16,
    HAZEMON_C4H10            = 17,
    HAZEMON_CH4              = 18,
    HAZEMON_H2               = 19,
    HAZEMON_C2H5OH           = 20,
    HAZEMON_UV               = 21,
    HAZEMON_MQ7_CO           = 22,
    HAZEMON_WZS_HCHO         = 23,
    HAZEMON_MHZ16_CO2        = 24,
    HAZEMON_RAIN             = 25,
    HAZEMON_WIND_SPD         = 26,
    HAZEMON_WIND_DIR         = 27,
    HAZEMON_AX               = 28,
    HAZEMON_AY               = 29,
    HAZEMON_AZ               = 30,
    HAZEMON_GX               = 31,
    HAZEMON_GY               = 32,
    HAZEMON_GZ               = 33,
    HAZEMON_MX               = 34,
    HAZEMON_MY               = 35,
    HAZEMON_MZ               = 36,
    HAZEMON_TEMP_AOSONG      = 37,
    HAZEMON_HUMI_AOSONG      = 38,
    HAZEMON_TOUPLOAD         = 39,
    HAZEMON_GASRES           = 40,
    HAZEMON_TVOC             = 41,
    HAZEMON_ECO2             = 42,
    HAZEMON_RAWH2            = 43,
    HAZEMON_RAWETHANOL       = 44,
    HAZEMON_VERSION          = 45,
    HAZEMON_TIMESTAMP        = 234,

    HAZEMON_TYPE_LAST,
} hazemon_type_t;

typedef struct hazemon_type_token_s {
   const char       *token;
   hazemon_type_t   type;
   const char       *datatype;
   float            multiplier;
} hazemon_type_token_t;


const hazemon_type_token_t *can5_hazemon_get_type(const hazemon_type_t type);
const hazemon_type_token_t *can5_hazemon_get_token(const char *token);
const char *hazemon_type_str(const hazemon_type_t type);

#endif /* __CAN5_HAZEMON_TYPES_H__ */