/*
 * Auto generated by scripts/generate/generate_hazemon_types.py
 */

#include "can5_hazemon_types.h"
#include <string.h>
#include "can5_utils.h"


static const hazemon_type_token_t hazemon_type_tokens[] = {
    { "INTERVAL"               , HAZEMON_INTERVAL        , "B"      , 1       },
    { "GPS_LAT"                , HAZEMON_GPS_LAT         , "f"      , 1       },
    { "GPS_LNG"                , HAZEMON_GPS_LNG         , "f"      , 1       },
    { "GPS_ALT"                , HAZEMON_GPS_ALT         , "h"      , 1       },
    { "TEMPERATURE"            , HAZEMON_TEMPERATURE     , "h"      , 0.1     },
    { "HUMIDITY"               , HAZEMON_HUMIDITY        , "H"      , 0.1     },
    { "PRESSURE"               , HAZEMON_PRESSURE        , "H"      , 0.1     },
    { "PM2_5"                  , HAZEMON_PM2_5           , "H"      , 1       },
    { "PM10"                   , HAZEMON_PM10            , "H"      , 1       },
    { "PM1_0"                  , HAZEMON_PM1_0           , "H"      , 1       },
    { "BATT_V"                 , HAZEMON_BATT_V          , "H"      , 0.001   },
    { "FORMALDEHYDE"           , HAZEMON_FORMALDEHYDE    , "f"      , 0.001   },
    { "STATUS"                 , HAZEMON_STATUS          , "string" , 1       },
    { "NH3"                    , HAZEMON_NH3             , "f"      , 0.1     },
    { "CO"                     , HAZEMON_CO              , "f"      , 0.1     },
    { "NO2"                    , HAZEMON_NO2             , "H"      , 1       },
    { "C3H8"                   , HAZEMON_C3H8            , "f"      , 0.1     },
    { "C4H10"                  , HAZEMON_C4H10           , "f"      , 0.1     },
    { "CH4"                    , HAZEMON_CH4             , "f"      , 0.1     },
    { "H2"                     , HAZEMON_H2              , "f"      , 0.1     },
    { "C2H5OH"                 , HAZEMON_C2H5OH          , "f"      , 0.1     },
    { "UV"                     , HAZEMON_UV              , "f"      , 0.1     },
    { "MQ7_CO"                 , HAZEMON_MQ7_CO          , "f"      , 0.1     },
    { "WZS_HCHO"               , HAZEMON_WZS_HCHO        , "H"      , 0.001   },
    { "MHZ16_CO2"              , HAZEMON_MHZ16_CO2       , "H"      , 1       },
    { "RAIN"                   , HAZEMON_RAIN            , "f"      , 1       },
    { "WIND_SPD"               , HAZEMON_WIND_SPD        , "f"      , 1       },
    { "WIND_DIR"               , HAZEMON_WIND_DIR        , "f"      , 1       },
    { "AX"                     , HAZEMON_AX              , "h"      , 1       },
    { "AY"                     , HAZEMON_AY              , "h"      , 1       },
    { "AZ"                     , HAZEMON_AZ              , "h"      , 1       },
    { "GX"                     , HAZEMON_GX              , "h"      , 1       },
    { "GY"                     , HAZEMON_GY              , "h"      , 1       },
    { "GZ"                     , HAZEMON_GZ              , "h"      , 1       },
    { "MX"                     , HAZEMON_MX              , "h"      , 1       },
    { "MY"                     , HAZEMON_MY              , "h"      , 1       },
    { "MZ"                     , HAZEMON_MZ              , "h"      , 1       },
    { "TEMP_AOSONG"            , HAZEMON_TEMP_AOSONG     , "h"      , 0.1     },
    { "HUMI_AOSONG"            , HAZEMON_HUMI_AOSONG     , "h"      , 0.1     },
    { "TOUPLOAD"               , HAZEMON_TOUPLOAD        , "L"      , 1       },
    { "GASRES"                 , HAZEMON_GASRES          , "H"      , 1       },
    { "TVOC"                   , HAZEMON_TVOC            , "H"      , 1       },
    { "ECO2"                   , HAZEMON_ECO2            , "H"      , 1       },
    { "RAWH2"                  , HAZEMON_RAWH2           , "H"      , 1       },
    { "RAWETHANOL"             , HAZEMON_RAWETHANOL      , "H"      , 1       },
    { "VERSION"                , HAZEMON_VERSION         , "H"      , 1       },
    { "TIMESTAMP"              , HAZEMON_TIMESTAMP       , "Q"      , 1       },

};


const hazemon_type_token_t *can5_hazemon_get_type(const hazemon_type_t type)
{
    for(size_t i = 0; i < sizeof(hazemon_type_tokens)/sizeof(hazemon_type_tokens[0]); i ++) {
        if (hazemon_type_tokens[i].type == type) {
            return &hazemon_type_tokens[i];
        }
    }
    return NULL;
}


const hazemon_type_token_t *can5_hazemon_get_token(const char *token)
{
    for(size_t i = 0; i < sizeof(hazemon_type_tokens)/sizeof(hazemon_type_tokens[0]); i ++) {
        if (strcmp(hazemon_type_tokens[i].token, token) == 0) {
            return &hazemon_type_tokens[i];
        }
    }
    return NULL;
}


static const can5_tag_tab_t __hazemon_type_tags = {
    TAG_TAB_ITEM(HAZEMON_INTERVAL        ),
    TAG_TAB_ITEM(HAZEMON_GPS_LAT         ),
    TAG_TAB_ITEM(HAZEMON_GPS_LNG         ),
    TAG_TAB_ITEM(HAZEMON_GPS_ALT         ),
    TAG_TAB_ITEM(HAZEMON_TEMPERATURE     ),
    TAG_TAB_ITEM(HAZEMON_HUMIDITY        ),
    TAG_TAB_ITEM(HAZEMON_PRESSURE        ),
    TAG_TAB_ITEM(HAZEMON_PM2_5           ),
    TAG_TAB_ITEM(HAZEMON_PM10            ),
    TAG_TAB_ITEM(HAZEMON_PM1_0           ),
    TAG_TAB_ITEM(HAZEMON_BATT_V          ),
    TAG_TAB_ITEM(HAZEMON_FORMALDEHYDE    ),
    TAG_TAB_ITEM(HAZEMON_STATUS          ),
    TAG_TAB_ITEM(HAZEMON_NH3             ),
    TAG_TAB_ITEM(HAZEMON_CO              ),
    TAG_TAB_ITEM(HAZEMON_NO2             ),
    TAG_TAB_ITEM(HAZEMON_C3H8            ),
    TAG_TAB_ITEM(HAZEMON_C4H10           ),
    TAG_TAB_ITEM(HAZEMON_CH4             ),
    TAG_TAB_ITEM(HAZEMON_H2              ),
    TAG_TAB_ITEM(HAZEMON_C2H5OH          ),
    TAG_TAB_ITEM(HAZEMON_UV              ),
    TAG_TAB_ITEM(HAZEMON_MQ7_CO          ),
    TAG_TAB_ITEM(HAZEMON_WZS_HCHO        ),
    TAG_TAB_ITEM(HAZEMON_MHZ16_CO2       ),
    TAG_TAB_ITEM(HAZEMON_RAIN            ),
    TAG_TAB_ITEM(HAZEMON_WIND_SPD        ),
    TAG_TAB_ITEM(HAZEMON_WIND_DIR        ),
    TAG_TAB_ITEM(HAZEMON_AX              ),
    TAG_TAB_ITEM(HAZEMON_AY              ),
    TAG_TAB_ITEM(HAZEMON_AZ              ),
    TAG_TAB_ITEM(HAZEMON_GX              ),
    TAG_TAB_ITEM(HAZEMON_GY              ),
    TAG_TAB_ITEM(HAZEMON_GZ              ),
    TAG_TAB_ITEM(HAZEMON_MX              ),
    TAG_TAB_ITEM(HAZEMON_MY              ),
    TAG_TAB_ITEM(HAZEMON_MZ              ),
    TAG_TAB_ITEM(HAZEMON_TEMP_AOSONG     ),
    TAG_TAB_ITEM(HAZEMON_HUMI_AOSONG     ),
    TAG_TAB_ITEM(HAZEMON_TOUPLOAD        ),
    TAG_TAB_ITEM(HAZEMON_GASRES          ),
    TAG_TAB_ITEM(HAZEMON_TVOC            ),
    TAG_TAB_ITEM(HAZEMON_ECO2            ),
    TAG_TAB_ITEM(HAZEMON_RAWH2           ),
    TAG_TAB_ITEM(HAZEMON_RAWETHANOL      ),
    TAG_TAB_ITEM(HAZEMON_VERSION         ),
    TAG_TAB_ITEM(HAZEMON_TIMESTAMP       ),

};


const char *hazemon_type_str(const hazemon_type_t type)
{
    return TAG_LOOKUP(type, __hazemon_type_tags);
}

